apiVersion: v1
kind: ReplicationController
metadata:
  name: app1-rc
  labels:
    app: app1
    type: front-end
spec:
  template:
    metadata:
      name: mypod
      labels:
        app: app1
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
  replicas: 2

