apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app1-rs
  labels:
    app: app1
    type: front-end
spec:
  template:
    metadata:
      name: app1-pod
      labels:
        app: app1
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
  replicas: 6
  selector:
    matchLabels:
      app: app1
      type: front-end
