apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: app-votation
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
      app: app-votation
  template:
    metadata:
      name: redis
      labels:
        name: redis
        app: app-votation
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: redis
          
