apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels: 
    name: redis
    app: app-votation
spec:
  type: ClusterIP
  ports: 
  - port: 6379
    targetPort: 6379
    name: "redis-service"
  selector:
    name: redis
    app: app-votation